import React from "react";

const TermsOfServicePage = () => {
  return (
    <div className="legal-page tos-page">
      <header className="legal-header">
        <p className="eyebrow">Legal</p>
        <h1>Terms of Service</h1>
        <div className="legal-meta">
          <span><strong>Effective:</strong> [DATE]</span>
          <span><strong>Last Reviewed:</strong> [DATE]</span>
          <span><strong>Version:</strong> 1.0</span>
        </div>
      </header>

      <section className="legal-section">
        <h2><span className="section-num">2.1</span> Agreement to Terms</h2>
        <p>
          These Terms of Service ("Terms") constitute a legally binding agreement
          between you ("User," "you," or "your") and <strong>[Woven Legal Entity Name]</strong>,
          a company incorporated under the laws of the Federal Republic of Nigeria,
          governing your access to and use of woven.so and all associated services
          (the "Platform").
        </p>
        <p>
          By accessing, registering for, or using the Platform, you acknowledge that
          you have read, understood, and agree to be bound by these Terms.
        </p>
        <p className="legal-highlight">
          <strong>Eligibility:</strong> You must be at least eighteen (18) years of
          age, or the age of majority in your jurisdiction, whichever is greater.
        </p>
      </section>

      <section className="legal-section">
        <h2><span className="section-num">2.2</span> Description of Services</h2>
        <p>Woven provides a social media publishing and AI-assisted content creation platform. The Platform enables Users to:</p>
        <ul className="legal-list">
          <li>Generate AI-assisted captions and content variants</li>
          <li>Schedule and publish content to connected social media accounts</li>
          <li>Utilize the Mobile Push Queue as a publishing fallback mechanism</li>
          <li>Access AI Chat assistance with Human-in-the-Loop escalation (Phase 2)</li>
          <li>Manage credits for AI operations</li>
        </ul>
        <p className="legal-note">
          Woven is a <strong>tool provider</strong>, not a publisher. The User retains
          full responsibility for all content created, scheduled, or published.
        </p>
      </section>

      <section className="legal-section">
        <h2><span className="section-num">2.3</span> Account Registration and Security</h2>
        <p><strong>2.3.1</strong> You agree to provide accurate, current, and complete information during registration.</p>
        <p><strong>2.3.2</strong> You are solely responsible for maintaining the confidentiality of your credentials.</p>
        <p><strong>2.3.3</strong> You must notify Woven immediately of any unauthorized access or security breach.</p>
        <p><strong>2.3.4</strong> Accounts are personal and non-transferable unless expressly authorized.</p>
        <p><strong>2.3.5</strong> Woven reserves the right to suspend or terminate accounts that violate these Terms.</p>
      </section>

      <section className="legal-section">
        <h2><span className="section-num">2.4</span> AI-Generated Content</h2>
        <div className="tos-subsection">
          <h3>2.4.1 Ownership</h3>
          <p>Subject to your compliance with these Terms, you retain all rights, title, and interest in content generated by the Platform's AI systems on your behalf ("Output"). Woven claims no ownership over your Output.</p>
        </div>
        <div className="tos-subsection">
          <h3>2.4.2 Responsibility</h3>
          <p>You acknowledge that AI-generated content may be inaccurate, incomplete, or unsuitable. You are solely responsible for reviewing, editing, and approving all Output prior to publication.</p>
        </div>
        <div className="tos-subsection">
          <h3>2.4.3 Regulated Industries</h3>
          <p>Users operating in regulated sectors (healthcare, finance, legal, insurance) agree to implement enhanced review procedures.</p>
        </div>
        <div className="tos-subsection">
          <h3>2.4.4 No Warranty of Originality</h3>
          <p>Woven does not warrant that Output is original, non-infringing, or suitable for any particular purpose.</p>
        </div>
      </section>

      <section className="legal-section">
        <h2><span className="section-num">2.5</span> Credits, Billing, and Payment</h2>
        <p><strong>2.5.1 Credit System.</strong> Credits constitute Woven's internal currency for AI operations. Credits are non-transferable and hold no cash value outside the Platform.</p>
        <p><strong>2.5.2 Non-Expiration.</strong> Purchased credits do not expire and remain available indefinitely.</p>
        <p><strong>2.5.3 Auto-Refund.</strong> Failed AI operations and API publishing failures trigger automatic credit refunds within five (5) seconds.</p>
        <p><strong>2.5.4 Non-Refundable Consumption.</strong> Credits consumed by successful operations are non-refundable.</p>
        <p><strong>2.5.5 Pricing.</strong> Prices are denominated in USD (Stripe) or NGN (Paystack) based on billing region. Woven reserves the right to modify pricing with thirty (30) days' notice.</p>
        <p><strong>2.5.6 Taxes.</strong> You are responsible for all applicable taxes, duties, and levies.</p>
      </section>

      <section className="legal-section">
        <h2><span className="section-num">2.6</span> Third-Party Platform Compliance</h2>
        <p><strong>2.6.1</strong> You agree to comply with all applicable terms of service of Connected Platforms.</p>
        <p><strong>2.6.2</strong> Woven shall not be liable for:</p>
        <ul className="legal-list">
          <li>Changes to Connected Platform APIs, policies, or availability</li>
          <li>Account restrictions imposed by Connected Platforms</li>
          <li>Content removal or moderation by Connected Platforms</li>
          <li>Delays or failures in publishing caused by Connected Platforms</li>
        </ul>
        <p><strong>2.6.3 Mobile Push Queue.</strong> Where API publishing fails, Woven routes content to the Mobile Push Queue. Completion of publishing remains the User's responsibility.</p>
      </section>

      <section className="legal-section">
        <h2><span className="section-num">2.7</span> Acceptable Use</h2>
        <p>You agree not to use the Platform to:</p>
        <ul className="legal-list">
          <li>Violate any applicable law or regulation</li>
          <li>Infringe intellectual property rights</li>
          <li>Transmit harassing, defamatory, obscene, or hateful content</li>
          <li>Impersonate any person or entity</li>
          <li>Distribute spam, malware, or phishing content</li>
          <li>Reverse-engineer, decompile, or scrape the Platform</li>
          <li>Circumvent credit limits, payment obligations, or security measures</li>
          <li>Make medical, financial, or legal claims without human verification</li>
          <li>Engage in any activity that disrupts or impairs the Platform</li>
        </ul>
      </section>

      <section className="legal-section">
        <h2><span className="section-num">2.8</span> AI Chat (Phase 2)</h2>
        <p><strong>2.8.1</strong> AI Chat operates under a Human-in-the-Loop model. The AI auto-replies only to low-risk, simple conversations meeting defined confidence thresholds.</p>
        <p><strong>2.8.2</strong> Complex, sensitive, or low-confidence conversations escalate to the User.</p>
        <p><strong>2.8.3</strong> The User is responsible for all replies sent from their account.</p>
        <p><strong>2.8.4</strong> The User agrees to configure escalation rules appropriate to their business and industry.</p>
      </section>

      <section className="legal-section">
        <h2><span className="section-num">2.9</span> Intellectual Property</h2>
        <p><strong>2.9.1 Woven IP.</strong> The Platform, including all software, code, design, trademarks, and documentation, is owned by Woven and protected by applicable intellectual property laws.</p>
        <p><strong>2.9.2 User Content.</strong> You retain ownership of all content you upload, create, or publish via the Platform.</p>
        <p><strong>2.9.3 License Grant.</strong> You grant Woven a limited, non-exclusive, worldwide, royalty-free license to store, process, transmit, and display your content solely as necessary to provide the Platform.</p>
        <p><strong>2.9.4 Feedback.</strong> Any feedback, suggestions, or ideas you provide may be used by Woven without restriction or compensation.</p>
      </section>

      <section className="legal-section">
        <h2><span className="section-num">2.10</span> Disclaimers</h2>
        <div className="tos-disclaimer">
          <p>THE PLATFORM IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.</p>
          <p>WOVEN DOES NOT WARRANT THAT:</p>
          <ul className="legal-list">
            <li>THE PLATFORM WILL BE UNINTERRUPTED OR ERROR-FREE</li>
            <li>AI OUTPUT WILL MEET YOUR EXPECTATIONS</li>
            <li>CONNECTED PLATFORMS WILL REMAIN AVAILABLE</li>
            <li>SCHEDULED POSTS WILL PUBLISH WITHOUT FAILURE</li>
          </ul>
        </div>
      </section>

      <section className="legal-section">
        <h2><span className="section-num">2.11</span> Limitation of Liability</h2>
        <p>
          TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, WOVEN SHALL NOT BE
          LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE
          DAMAGES, INCLUDING LOSS OF PROFITS, REVENUE, DATA, OR GOODWILL.
        </p>
        <p className="legal-highlight">
          WOVEN'S TOTAL AGGREGATE LIABILITY SHALL NOT EXCEED THE AMOUNTS PAID BY YOU
          IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM.
        </p>
      </section>

      <section className="legal-section">
        <h2><span className="section-num">2.12</span> Indemnification</h2>
        <p>You agree to indemnify, defend, and hold harmless Woven, its officers, directors, employees, and agents from any claims, damages, losses, or expenses arising from:</p>
        <ul className="legal-list">
          <li>Your use of the Platform</li>
          <li>Your violation of these Terms</li>
          <li>Your violation of any third-party rights</li>
          <li>Content you publish via the Platform</li>
        </ul>
      </section>

      <section className="legal-section">
        <h2><span className="section-num">2.13</span> Termination</h2>
        <p><strong>2.13.1 By User.</strong> You may terminate your account at any time via account settings.</p>
        <p><strong>2.13.2 By Woven.</strong> We may suspend or terminate your account for violation of these Terms.</p>
        <p><strong>2.13.3 Effect.</strong> Upon termination, your right to use the Platform ceases immediately. Unused purchased credits are forfeited unless required otherwise by applicable law.</p>
      </section>

      <section className="legal-section">
        <h2><span className="section-num">2.14</span> Governing Law and Dispute Resolution</h2>
        <p>
          These Terms are governed by the laws of the Federal Republic of Nigeria.
          Any dispute shall be resolved in the courts of Lagos State, Nigeria, unless
          mandatory consumer protection laws in your jurisdiction provide otherwise.
        </p>
      </section>

      <section className="legal-section">
        <h2><span className="section-num">2.15</span> Modifications</h2>
        <p>
          Woven reserves the right to modify these Terms. Material changes will be
          communicated not less than fourteen (14) days prior to the effective date.
        </p>
      </section>

      <section className="legal-section">
        <h2><span className="section-num">2.16</span> Miscellaneous</h2>
        <p><strong>2.16.1 Entire Agreement.</strong> These Terms constitute the entire agreement between you and Woven.</p>
        <p><strong>2.16.2 Severability.</strong> If any provision is held unenforceable, the remaining provisions remain in full force.</p>
        <p><strong>2.16.3 Waiver.</strong> Failure to enforce any provision does not constitute a waiver.</p>
        <p><strong>2.16.4 Assignment.</strong> You may not assign these Terms without Woven's consent. Woven may assign freely.</p>
      </section>

      <section className="legal-section contact-block">
        <h2><span className="section-num">2.17</span> Contact</h2>
        <div className="contact-card-legal">
          <p><strong>Legal Department</strong></p>
          <p>[Woven Legal Entity Name]</p>
          <p>[Registered Address]</p>
          <p>Email: <a href="mailto:legal@woven.so">legal@woven.so</a></p>
        </div>
      </section>
    </div>
  );
};

export default TermsOfServicePage;